### ISSUE TITLE
Not Support this Telemetry sdk Version

### ISSUE THREAD

**Issue by DTheIcyDragon** [Dreagonmon/truck_telemetry#1]
https://github.com/Dreagonmon/truck_telemetry/blob/main/truck_telemetry/truck_telemetry.py#L7-L15

```py
def init():
    global _mem, _telemetry_sdk_version
    _mem = SharedMemory(name="Local\\SCSTelemetry", create=False)
    for version in (v1_10,):
        if (version.is_same_version(_mem.buf)):
            _telemetry_sdk_version = version
            break
    if _telemetry_sdk_version == None:
        raise Exception("Not support this telemetry sdk version")
```

The Problem: 
The code errors because [here](https://github.com/Dreagonmon/truck_telemetry/blob/main/truck_telemetry/telemetry_version/v1_10.py) the memory adress is != to the version number.)

However if you just skip it (I just passed true through it) the package still works

I'd also love to create a pull request but my knowledge how to work with memory adresses is not good enough.

I'd greatly appreciate a response :)

**Comment by Dreagonmon** [comment]
https://github.com/RenCloud/scs-sdk-plugin/blob/5cec527a4d9f0927546bc6a7885322ffe2de16ed/scs-telemetry/inc/scs-telemetry-common.hpp#L146

the version number's offset is 40 bytes.
(1bool 3bytes 1bool 3bytes 3longlong 8bytes, totally 40 bytes)

https://github.com/Dreagonmon/truck_telemetry/blob/e353585940ff40949e836bb8d27671aab014dbcd/truck_telemetry/telemetry_version/v1_10.py#L8

here the version number's offset is also 40 bytes (40x)

it is matched. you must use the same plugin version 1.10. otherwise the version number will not match, for your safety the program throw an exception.

**Comment by Dreagonmon** [comment]
if you need to use a newer version, you should create a new memory map. different plugin version may have different memory map, thats why this exception exists.

**Comment by DTheIcyDragon** [comment]
Thanks for the quick response, I'll look into it. If I am able to update the memory map I'll create a pull request

**Comment by DTheIcyDragon** [comment]
Created a pull request to this issue #2
